/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.mavenproject1;

import java.awt.Color;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ayat
 */
public class AddOrder extends javax.swing.JFrame {

    connection con = new connection();
    static DefaultTableModel itmsTb = new DefaultTableModel();

    /**
     * Creates new form AddOrder
     */
    public AddOrder() {
        initComponents();
        itmsTb = (DefaultTableModel) itms.getModel();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ClientsBox = new javax.swing.JComboBox<>();
        Add1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        discount = new javax.swing.JCheckBox();
        discountText = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        itms = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(1, 31, 75)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Dosis Medium", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(1, 31, 75));
        jLabel7.setText("Add Order");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, -1, 90));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(1, 31, 75));
        jLabel8.setText("%");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 470, 40, 30));

        ClientsBox.setBackground(new Color(0,0,0,0));
        ClientsBox.setForeground(new java.awt.Color(3, 57, 108));
        try{
            ClientsBox.setModel(new DefaultComboBoxModel(new connection().ClientTable() ));
        }
        catch(Exception e){}
        ClientsBox.setSelectedItem("");
        ClientsBox.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(1, 31, 75)));
        ClientsBox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ClientsBox.setPreferredSize(new java.awt.Dimension(78, 22));
        ClientsBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClientsBoxActionPerformed(evt);
            }
        });
        jPanel3.add(ClientsBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, 350, 30));

        Add1.setBackground(new java.awt.Color(3, 57, 108));
        Add1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Add1.setForeground(new java.awt.Color(179, 205, 224));
        Add1.setText("Add");
        Add1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Add1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add1ActionPerformed(evt);
            }
        });
        jPanel3.add(Add1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 520, 100, 30));

        jPanel4.setBackground(new java.awt.Color(0, 91, 150));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ayat\\Desktop\\mavenproject1 (2)\\mavenproject1\\images\\add_order-200.png")); // NOI18N
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 270, 280));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 580));

        jLabel19.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ayat\\Desktop\\mavenproject1 (2)\\mavenproject1\\images\\icons8_cancel_filled_35px.png")); // NOI18N
        jLabel19.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(715, 0, 40, 40));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(1, 31, 75));
        jLabel10.setText("Client");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, 130, 20));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(1, 31, 75));
        jLabel11.setText("Products");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, 90, 20));

        discount.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        discount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                discountMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                discountMousePressed(evt);
            }
        });
        discount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discountActionPerformed(evt);
            }
        });
        jPanel3.add(discount, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 440, -1, -1));

        discountText.setEditable(false);
        discountText.setBackground(ClientsBox.getBackground());
        discountText.setFont(ClientsBox.getFont());
        discountText.setForeground(ClientsBox.getForeground());
        discountText.setText("0");
        discountText.setBorder(ClientsBox.getBorder());
        discountText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discountTextActionPerformed(evt);
            }
        });
        jPanel3.add(discountText, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 470, 320, 30));

        itms.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ref", "Wording", "Price unit", "Select", "Quantity"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        itms.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        itms.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                itmsMouseExited(evt);
            }
        });
        jScrollPane1.setViewportView(itms);
        if (itms.getColumnModel().getColumnCount() > 0) {
            itms.getColumnModel().getColumn(0).setResizable(false);
            itms.getColumnModel().getColumn(0).setPreferredWidth(20);
            itms.getColumnModel().getColumn(1).setResizable(false);
            itms.getColumnModel().getColumn(2).setResizable(false);
            itms.getColumnModel().getColumn(2).setPreferredWidth(35);
            itms.getColumnModel().getColumn(3).setResizable(false);
            itms.getColumnModel().getColumn(3).setPreferredWidth(30);
            itms.getColumnModel().getColumn(4).setResizable(false);
            itms.getColumnModel().getColumn(4).setPreferredWidth(30);
        }

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 350, 160));

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(1, 31, 75));
        jLabel14.setText("Discount");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 440, 90, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void discountTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discountTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_discountTextActionPerformed

    private void discountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_discountActionPerformed

    private void discountMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_discountMousePressed
        // TODO add your handling code here:
        if (discount.isSelected()) {
            discountText.setText("0");
            discountText.setEditable(false);
        } else {
            discountText.setEditable(true);
        }

    }//GEN-LAST:event_discountMousePressed

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel19MouseClicked

    private void Add1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add1ActionPerformed
        // TODO add your handling code here:
        if (itms.getCellEditor() != null) {
            itms.getCellEditor().stopCellEditing();
        }

        String str = ClientsBox.getSelectedItem().toString();
        int index1 = str.indexOf("(") + 1;
        int index2 = str.indexOf(")");
        int clientID = Integer.parseInt(str.substring(index1, index2));

        try {
            //insert to orders
            con.insertOrder(clientID, Float.parseFloat(discountText.getText()));

        } catch (Exception ex) {
            Logger.getLogger(AddOrder.class.getName()).log(Level.SEVERE, null, ex);
        }
        //boucle -> insert to orderItems           
        DefaultTableModel itm = (DefaultTableModel) itms.getModel();
        int option;
        JFrame frame = new JFrame();
        String[] options = new String[2];
        for (int i = 0; i < itm.getRowCount(); i++) {

            if (itms.getValueAt(i, 3) != null && (boolean) itms.getValueAt(i, 3)) {

                try {
                    con.insertOrderItem(itms.getValueAt(i, 0).toString(), Integer.parseInt(itms.getValueAt(i, 4).toString()));
                } catch (Exception ex) {
                }
            }

        }
        // total = total (1- discount)
        try {
            //update orders set total = total
            con.UpdateTotalInset();
        } catch (Exception ex) {
            Logger.getLogger(AddOrder.class.getName()).log(Level.SEVERE, null, ex);
        }
        NewJFrame.Card.removeAll();
        NewJFrame.Card.add(NewJFrame.Orders);
        NewJFrame.Card.repaint();
        NewJFrame.Card.revalidate();
        NewJFrame.fr1.refreshOrders();

        this.dispose();
    }//GEN-LAST:event_Add1ActionPerformed

    private void ClientsBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClientsBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClientsBoxActionPerformed

    private void discountMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_discountMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_discountMouseExited

    private void itmsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itmsMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_itmsMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddOrder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add1;
    private javax.swing.JComboBox<String> ClientsBox;
    private javax.swing.JCheckBox discount;
    private javax.swing.JTextField discountText;
    public static javax.swing.JTable itms;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
