/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.mavenproject1;

import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Ayat
 */
public class AddProduct extends javax.swing.JFrame  {
    connection con = new connection();

    /**
     * Creates new form AddClient
     */
    public AddProduct() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pTVA = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        pWord = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        FamilyBox = new javax.swing.JComboBox<>();
        Addproduct = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        CategoryBox = new javax.swing.JComboBox<>();
        pREF = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        pPU = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        pWord1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        pStock = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(1, 31, 75)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dosis Medium", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(1, 31, 75));
        jLabel1.setText("Add Product");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, -1, 90));

        jLabel2.setFont(new java.awt.Font("Dosis Medium", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(1, 31, 75));
        jLabel2.setText("Reference");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 110, 20));

        pTVA.setBackground(new Color(0,0,0,0));
        pTVA.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        pTVA.setForeground(new java.awt.Color(3, 57, 108));
        pTVA.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(1, 31, 75)));
        pTVA.setOpaque(false);
        pTVA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pTVAActionPerformed(evt);
            }
        });
        jPanel1.add(pTVA, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 490, 100, 30));

        jLabel4.setFont(new java.awt.Font("Dosis Medium", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(1, 31, 75));
        jLabel4.setText("MAD");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 490, 70, 30));

        pWord.setBackground(new Color(0,0,0,0));
        pWord.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        pWord.setForeground(new java.awt.Color(3, 57, 108));
        pWord.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(1, 31, 75)));
        pWord.setOpaque(false);
        pWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pWordActionPerformed(evt);
            }
        });
        jPanel1.add(pWord, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 300, 30));

        jLabel5.setFont(new java.awt.Font("Dosis Medium", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(1, 31, 75));
        jLabel5.setText("TVA");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 460, 110, 30));

        jLabel6.setFont(new java.awt.Font("Dosis Medium", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(1, 31, 75));
        jLabel6.setText("Category");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, 100, 30));

        jLabel7.setFont(new java.awt.Font("Dosis Medium", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(1, 31, 75));
        jLabel7.setText("Familly");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 320, 90, 30));

        FamilyBox.setBackground(new Color(0,0,0,0));
        FamilyBox.setFont(pTVA.getFont());
        FamilyBox.setForeground(new java.awt.Color(3, 57, 108));
        try{
            FamilyBox.setModel(new DefaultComboBoxModel(new connection().famillyTable() ));
        }
        catch(Exception e){}
        FamilyBox.setSelectedItem("");
        FamilyBox.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(1, 31, 75)));
        FamilyBox.setPreferredSize(new java.awt.Dimension(78, 22));
        FamilyBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FamilyBoxActionPerformed(evt);
            }
        });
        jPanel1.add(FamilyBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 350, 300, 30));

        Addproduct.setBackground(new java.awt.Color(3, 57, 108));
        Addproduct.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Addproduct.setForeground(new java.awt.Color(179, 205, 224));
        Addproduct.setText("Add");
        Addproduct.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Addproduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddproductActionPerformed(evt);
            }
        });
        jPanel1.add(Addproduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 540, 100, 30));

        jPanel2.setBackground(new java.awt.Color(0, 91, 150));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ayat\\Desktop\\mavenproject1 (2)\\mavenproject1\\images\\add-product (2).png")); // NOI18N
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 240, 280));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 600));

        jLabel18.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ayat\\Desktop\\mavenproject1 (2)\\mavenproject1\\images\\icons8_cancel_filled_30px.png")); // NOI18N
        jLabel18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(715, 0, 40, 40));

        CategoryBox.setBackground(new Color(0,0,0,0));
        CategoryBox.setFont(pTVA.getFont());
        CategoryBox.setForeground(new java.awt.Color(3, 57, 108));
        try{
            CategoryBox.setModel(new DefaultComboBoxModel(new connection().CategoryTable() ));
        }
        catch(Exception e){}
        CategoryBox.setSelectedItem("");
        CategoryBox.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(1, 31, 75)));
        CategoryBox.setPreferredSize(new java.awt.Dimension(78, 22));
        jPanel1.add(CategoryBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, 300, 30));

        pREF.setBackground(new Color(0,0,0,0));
        pREF.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        pREF.setForeground(new java.awt.Color(3, 57, 108));
        pREF.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(1, 31, 75)));
        pREF.setOpaque(false);
        pREF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pREFActionPerformed(evt);
            }
        });
        jPanel1.add(pREF, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, 300, 30));

        jLabel9.setFont(new java.awt.Font("Dosis Medium", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(1, 31, 75));
        jLabel9.setText("Wording");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, 110, 20));

        jLabel10.setFont(new java.awt.Font("Dosis Medium", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(1, 31, 75));
        jLabel10.setText("Price unit");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 460, 110, 30));

        pPU.setBackground(new Color(0,0,0,0));
        pPU.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        pPU.setForeground(new java.awt.Color(3, 57, 108));
        pPU.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(1, 31, 75)));
        pPU.setOpaque(false);
        pPU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pPUActionPerformed(evt);
            }
        });
        jPanel1.add(pPU, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 490, 100, 30));

        jLabel11.setFont(new java.awt.Font("Dosis Medium", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(1, 31, 75));
        jLabel11.setText("%");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 490, 40, 30));

        pWord1.setBackground(new Color(0,0,0,0));
        pWord1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        pWord1.setForeground(new java.awt.Color(3, 57, 108));
        pWord1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(1, 31, 75)));
        pWord1.setOpaque(false);
        pWord1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pWord1ActionPerformed(evt);
            }
        });
        jPanel1.add(pWord1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 300, 30));

        jLabel12.setFont(new java.awt.Font("Dosis Medium", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(1, 31, 75));
        jLabel12.setText("Wording");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, 110, 20));

        pStock.setBackground(new Color(0,0,0,0));
        pStock.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        pStock.setForeground(new java.awt.Color(3, 57, 108));
        pStock.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(1, 31, 75)));
        pStock.setOpaque(false);
        pStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pStockActionPerformed(evt);
            }
        });
        jPanel1.add(pStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 420, 300, 30));

        jLabel13.setFont(new java.awt.Font("Dosis Medium", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(1, 31, 75));
        jLabel13.setText("Stock");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 400, 110, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 752, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pTVAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pTVAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pTVAActionPerformed

    private void pWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pWordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pWordActionPerformed
   public boolean isNotEmpty(String text) {
        return !text.equals("");
    }
   public boolean isNumber(String text) {
        String regex = "[0-9]{1,8}";
        Pattern pattern = Pattern.compile(regex);
        Matcher matcher = pattern.matcher(text);
        return matcher.matches();
    }
    
    
    private void AddproductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddproductActionPerformed
        // TODO add your handling code here:
       if (!isNotEmpty(pREF.getText()) || !isNotEmpty(pWord.getText()) || !isNotEmpty(pPU.getText()) || !isNotEmpty(pTVA.getText()) || !isNotEmpty(pStock.getText())) 
            JOptionPane.showMessageDialog(new JFrame(), "there is an empty field  ");
      else{
           
           String str =  FamilyBox.getSelectedItem().toString();
           int index1 = str.indexOf("(") + 1;
           int index2 = str.indexOf(")");
           int familyID = Integer.parseInt(str.substring(index1, index2));
           
           str = CategoryBox.getSelectedItem().toString();
           index1 = str.indexOf("(") + 1;
           index2 = str.indexOf(")");
           int categoryID = Integer.parseInt(str.substring(index1, index2));
            
            try {
                con.insertProduct(pREF.getText(), pWord.getText(), categoryID, familyID,Float.parseFloat(pPU.getText()), Float.parseFloat(pTVA.getText()), Integer.parseInt(pStock.getText()));
            } catch (Exception ex) {
               // Logger.getLogger(AddClient.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        NewJFrame.Card.removeAll();
        NewJFrame.Card.add(NewJFrame.Products);
        NewJFrame.Card.repaint();
        NewJFrame.Card.revalidate();
        NewJFrame.fr1.refreshProduct();

           this.dispose();
       }
    }//GEN-LAST:event_AddproductActionPerformed

    private void pREFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pREFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pREFActionPerformed

    private void pPUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pPUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pPUActionPerformed

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel18MouseClicked

    private void FamilyBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FamilyBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FamilyBoxActionPerformed

    private void pWord1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pWord1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pWord1ActionPerformed

    private void pStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pStockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pStockActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JFrame clt = new AddProduct();
                clt.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Addproduct;
    private javax.swing.JComboBox<String> CategoryBox;
    private javax.swing.JComboBox<String> FamilyBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField pPU;
    private javax.swing.JTextField pREF;
    private javax.swing.JTextField pStock;
    private javax.swing.JTextField pTVA;
    private javax.swing.JTextField pWord;
    private javax.swing.JTextField pWord1;
    // End of variables declaration//GEN-END:variables
}
